### ISSUE TITLE
Connect via VPN

### ISSUE THREAD

**Issue by etomarat** [muflone/pykerio#2]
Hello! Thank you for your work!
Please tell me, can I programmatically establish a VPN connection using PyKerio through Kerio Control VPN Client or can PyKerio directly connect as a VPN client so that I can make some http requests?

**Comment by muflone** [comment]
Hi
PyKerio is an API to control a Kerio Control server, so you can start and stop tunnels

You can't connect as a VPN client as it's not a client library
